---
title: "Heart-Brain Network"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}

library(ProjectTemplate)
load.project()

```

```{r}

df <- readRDS("<PROJECT_ROOT>/04_NETWORK/data/df_imp.rds")
#df <- readRDS("<PROJECT_ROOT>/04_NETWORK/data/df_imp.rds")

```

```{r}

library(dplyr)
library(broom)
library(flextable)
library(caret)
library(bnlearn)
library(arules)
library(bnviewer)
library(purrr)

```

```{r}

magma_colors <- viridis::magma(10)  # Generate a 10-color magma palette
custom_palette <- c(magma_colors[3], magma_colors[6], magma_colors[9]) 
custom_palette_2 <- c(magma_colors[2], magma_colors[4], magma_colors[6], 
magma_colors[8], magma_colors[10])

```

```{r}
# Select only numeric columns
numeric_vars <- df %>% select(where(is.numeric))

# Discretize only numeric columns
df_discrete_numeric <- bnlearn::discretize(numeric_vars, method = "hartemink", 
                                           breaks=5, ibreaks=10)

# Combine back with non-numeric columns
df_discrete <- bind_cols(df %>% select(where(negate(is.numeric))), df_discrete_numeric)


```

```{r}

names(df_discrete) <- gsub("T0_", "", names(df_discrete))
names(df_discrete) <- gsub("_E1_C1", "", names(df_discrete))
names(df_discrete) <- gsub("_E1_C6", "", names(df_discrete))

names(df_discrete) <- make.names(names(df_discrete))
names(df_discrete) <- toupper(names(df_discrete))
```

```{r}
saveRDS(df_discrete, file="data/df_bn.RDS")
write.csv(df_discrete, file="data/df_bn.csv", row.names = FALSE)
```

```{r}

df_cdr <- df_discrete %>% 
  select(-outcome_composite, -Event_Stroke, -Event_MACE)

saveRDS(df_cdr, file="df_cdr.RDS")
write.csv(df_cdr, file="df_cdr.csv", row.names = FALSE)

```

```{r}
df_cdr <- readRDS("df_cdr.RDS")
```


```{r}

set.seed(52)
# Create training (80%) and test (20%) index
train_index <- createDataPartition(df_cdr$CDR_INCR, p = 0.8, list = FALSE)

# Split the dataset
df_train <- df_cdr[train_index, ]  # Training set
df_test  <- df_cdr[-train_index, ]  # Test set

```


```{r}
set.seed(44)

model <- tree.bayes(df_train, "CDR_INCR")
fitted <- bn.fit(model, df_train, method="bayes", iss=1)

pred.train = predict(fitted, df_train, prob=TRUE)
pred.test = predict(fitted, df_test, prob=TRUE)

table(pred.train, df_train[,"CDR_INCR"])
table(pred.test, df_test[,"CDR_INCR"])

```


```{r}
# Extract probability matrix
test_pred_probs <- attr(pred.test, "prob")
```

```{r}
set.seed(123)

# Extract only stable edges with confidence > 85%
stable_edges <- boot.strength(data = df_train, 
                              R = 50, 
                              algorithm = "tree.bayes",
                              algorithm.args=list(training="CDR_INCR"))

strong_edges <- averaged.network(stable_edges)

# 4. (Optional) If your averaged network is only partially directed,
# you can use cextend() to get a consistent DAG.
strong_edges <- cextend(strong_edges)

graphviz.plot(strong_edges, layout="fdp", render=TRUE, fontsize=30)

cv.tan = bn.cv("tree.bayes", data=df_train, runs=10, method="k-fold",
               folds=10, algorithm.args = list(training="CDR_INCR"))
cv.tan
plot(cv.tan)

graphviz.chart(fitted_strong, layout="fdp")

```

```{r}
strength.viewer(strong_edges,
                stable_edges, 
                bayesianNetwork.layout = "layout_nicely",
                bayesianNetwork.arc.strength.label = TRUE,
                bayesianNetwork.enabled.interactive.mode = TRUE,
                bayesianNetwork.width = "200%",
                bayesianNetwork.height = "200vh")
```


```{r}
cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (Age == "(59.4942,70.4956]") &
          (patientengroep == "Vascular cognitive impairment"))

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (Age == "(59.4942,70.4956]") &
          patientengroep == "Controle")

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (Age == "(59.4942,70.4956]") &
          patientengroep == "Hartfalen")

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (T0_NfL == "[4.43247,80.6807]"))

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (T0_NfL == "(80.6807,156.929]"))

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (T0_NfL == "(156.929,233.177]"))

cpquery(fitted, 
        event = (CDR_INCR == 1), 
        evidence = (T0_NfL == "(233.177,309.426]"))
```


